services:
  marshab-updater:
    build: .
    container_name: marshab-updater
    restart: unless-stopped
    ports:
      - "8141:80"
    networks:
      - Shared

networks:
  Shared:
    external: true
